version: "1.0"
info:
  model: int-scaffold
packages:
- name: PkgDemoANBAProject
  gitServerName: github_anbarbosa
  gitUrl: https://github.com/andresousabarbosa
  gitUsername: andresousabarbosa
  gitBranch: main
services:
- serviceName: project.pkgdemoanba.integrations:handleRequest
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
- serviceName: project.pkgdemoanba.integrations:serviceHello3
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
