version: "1.0"
info:
  model: int-scaffold
packages:
- name: CustomizeDev
  version: "1.0"
  gitServerName: github_anbarbosa
  gitUrl: https://github.com/andresousabarbosa
  gitUsername: andresousabarbosa
  gitBranch: main
- name: PkgDemoANBAProject
  gitServerName: github_anbarbosa
  gitUrl: https://github.com/andresousabarbosa
  gitUsername: andresousabarbosa
  gitBranch: main
services:
- serviceName: project.pkgdemoanba.integrations:getListNFeClient
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
  - name: CustomizeDev
    version: "1.0"
- serviceName: pub.json:jsonStringToDocument
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: project.pkgdemoanba.integrations:getPDFfromNFe
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
  - name: CustomizeDev
    version: "1.0"
- serviceName: project.pkgdemoanba.integrations:getQRCodefromNFe
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
  - name: CustomizeDev
    version: "1.0"
- serviceName: project.pkgdemoanba.integrations:handleRequest
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
  - name: CustomizeDev
    version: "1.0"
- serviceName: project.pkgdemoanba.integrations:send2ViaByEmail
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
  - name: CustomizeDev
    version: "1.0"
- serviceName: project.pkgdemoanba.integrations:testeService
  packages:
  - name: PkgDemoANBAProject
    version: "1.0"
  - name: CustomizeDev
    version: "1.0"
