version: "1.0"
projectName: PkgDemoANBAProject
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: getNFEInfo
    type: REST
    path: /getNFE
    action: POST
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:handleRequest
  - name: getNFEInfo
    type: REST
    path: /teste
    action: GET
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:testeService
  - name: NFEInfo
    type: REST
    path: /getNFE
    action: POST
    reference: fld_111498864_stage00.projects.fl94a5c649357a4808ba8481ecd1835f41.WmPackageServiceProvider.project.pkgdemoanba.integrations:handleRequest
  - name: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.integrations:teste
    type: flow
    stepId: /1
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.customizeDev.java:parserCSV
  - name: Customer
    type: REST
    path: /customers
    action: GET
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:customerList
  - name: Customer
    type: REST
    path: /createCustomer
    action: POST
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:customerInsert
  - name: Customer
    type: REST
    path: /customerById
    action: GET
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:customerGetById
  - name: Customer
    type: REST
    path: /customerAll
    action: GET
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:customerList2
