version: "1.0"
projectName: PkgDemoANBAProject
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: getNFEInfo
    type: REST
    path: /getNFE
    action: POST
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:handleRequest
  - name: getNFEInfo
    type: REST
    path: /teste
    action: GET
    reference: fld_111566327_stage00.projects.fl90df8caa77e84a00b55842fd7b7cc36c.WmPackageServiceProvider.project.pkgdemoanba.integrations:testeService
